### ISSUE TITLE
Sarah Drasner's Engineering Management book

### ISSUE THREAD

**Issue by cassidoo** [charlax/engineering-management#19]
I'd like to suggest Sarah Drasner's book, [Engineering Management for the Rest of Us](https://www.engmanagement.dev) for the list!

**Comment by charlax** [comment]
The book looks great, but I'd like to read it first before adding to the list (might get to that next year).

Btw: thanks for your newsletter :)

**Comment by cassidoo** [comment]
Sounds good! And thanks for your kind words :)
