### ISSUE TITLE
Page Not Found - Seven Deadly Diseases of Management

### ISSUE THREAD

**Issue by LS05** [charlax/engineering-management#5]
I've just found out in the README.md, that the link in this list item:
`Seven_ Deadly Diseases of Management, Dr. Deming. Great video as well. I don't necessarily agree with everything but Deming is still one of the great management thinker.`
Points to a "Not Found" page ;)

**Comment by charlax** [comment]
Indeed, looks like they changed the page URL. This is now fixed, thanks for the feedback!
